services:
  - type: web
    name: morphy-backend
    env: docker
    plan: starter
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://morphy-1-ulvv.onrender.com
    healthCheckPath: /health

  - type: web
    name: morphy-frontend
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: VITE_API_BASE_URL
        value: https://morphy-2-n2tb.onrender.com
 
